### ISSUE TITLE
Login feature not working

### ISSUE THREAD

**Issue by mobius1qwe** [Artentus/ModMyFactory2#10]
When I try to log in with my Factorio username and password like I used to in MMF it keeps returning me "A server-side error occured, please try again later."
Issue happens when you try to add login information in Settings window and when you attempt to download mods from the app.
I'm on Windows x64 standalone latest version on tag release.

**Comment by CaptainSilver** [comment]
Exact same issue here,  Windows x64 standalone latest v2.1.3.9-alpha

**Comment by Artentus** [comment]
Resolved in 2.1.4
