### ISSUE TITLE
Update Mods Issue

### ISSUE THREAD

**Issue by Dorky106** [Artentus/ModMyFactory2#15]
My resolution is 1920x1080
![image](https://user-images.githubusercontent.com/2104796/95679809-43ccc480-0ba3-11eb-94cc-6dbd61d3ad03.png)

**Comment by Artentus** [comment]
What's the issue?

**Comment by Dorky106** [comment]
The window cuts off, so you can't read what either of them do.

**Comment by Artentus** [comment]
Ah I see, will have a look at it

**Comment by Artentus** [comment]
Fixed
