### ISSUE TITLE
Window not displaying

### ISSUE THREAD

**Issue by fearofshorts** [Artentus/ModMyFactory2#16]
OS: Windows 10 Pro x64
Version: v4.0.2.19-beta, also tried with v4.0.2.18
Issue: The program opens just fine, but there is no window displayed. This is after getting a proper modpack set up and using it for a few days. After a crash and/or an update the issue appeared (I'm not sure which one caused it). The log ([attached](https://gist.github.com/fearofshorts/95b024c70d1565c763ba1945ee70728c)) seems to show it opening fine and working no problem, but there is no window visible on screen. I had ModMyFactoryGUI.exe pinned to the taskbar.

Windows shows the icon in the taskbar and I can bring the program to the foreground but there is nothing visible.

Please note that the window is not off screen (which I have had happen with a previous version of ModMyFactory2) as the usual fixes of "[Meta]+[Arrow Key]" or "[Shift]+RClick icon --> `cascade windows'" don't work.

Known workaround:
Removing my "ModMyFactoryGUI" folder from Appdata allows the program to open like normal, making me suspect that one or more files were corrupted at some point. I've slowly re-added files back to the directory and noticed that I could restore all of my files except "settings.json". For that reason, I've attached an anonymised version (with my credentials removed) [here](https://gist.github.com/fearofshorts/db7e6826c060303bb4e9a8d6c788e7a6) of the glitchy settings.json that seems to break the program.

No idea what caused this file to break, hopefully it's a simple fix

**Comment by Artentus** [comment]
So I have investigated this but so far I haven't got a clue why this happened.

You say the window was not offscreen but reading your config file suggests this as the most probable explanation. The coordinates are set to -32000, which is very very far out, although that still doesn't explain why cascade windows didn't work.

-32000 is a very specific value but I don't know why or how it was set to that. The log shows there was no error happening.

**Comment by TR-Mord-Sith** [comment]
Just wanted to drop in and say I had the same bug happen with 4.2.0.23-beta_universal.zip, it set the position and shrunk the screen after a few runs.

Win 10 Pro, running in Administrator Mode

**Comment by TR-Mord-Sith** [comment]
I may have figured it out, it seems that when you close the application while it's minimized, it saves the window's state at -32000 rather than it's state while it's viewable.

**Comment by Artentus** [comment]
Good find, will look into it right now
