### ISSUE TITLE
Location of mods

### ISSUE THREAD

**Issue by szentigrad3** [Artentus/ModMyFactory2#2]
when i set this to installation directory the app crashes and when i open it again  the setting has been reverted to default

**Comment by Artentus** [comment]
Have you run as administrator? Installation directory usually requires elevated privileges.

**Comment by szentigrad3** [comment]
i have and same problem

**Comment by szentigrad3** [comment]
just tried it also on my linux install same problem, also would like a unselect all mods option too

**Comment by Artentus** [comment]
Resolved
