### ISSUE TITLE
Factorio update

### ISSUE THREAD

**Issue by sync777** [Artentus/ModMyFactory2#20]
Will it be possible to update the already downloaded version of the game instead of downloading and installing it again?

**Comment by Artentus** [comment]
Use the ingame update of Factorio, it doesn't conflict with MMF at all.

**Comment by sync777** [comment]
> Use the ingame updater of Factorio, it doesn't conflict with MMF at all.

On Steam I play version 1.0 and in ModMyFactory I run the last experimental one. And with the release of each update, you have to download it again and through ModMyFactory it takes a very long time.

**Comment by Artentus** [comment]
No you don't. As I said, you can use the ingame updater.
