### ISSUE TITLE
Added Localization update

### ISSUE THREAD

**Issue by mobius1qwe** [Artentus/ModMyFactory2#21]
Changes
- Added Brazillian Portuguese localization languages and image.

Comments:
I was unable to make the context menu recognize properly the brazillian language: saving the .json file and the png as 'br.json' results in a different language name, saving as 'ptBR.json' doesn't gets recognized as a language, saving as pt was the only way to make it appear in the context menu. But its not the proper way to name it as ptPT stands for Portuguese from Portugal and ptBR stands for Portuguese from Brazil, altho they seem the same, there are lots of language differences between them.

I tried to commit directly to the repository but since it wasn't allowed I made this "issue" post to send the changes
Files: [ptBR.zip](https://github.com/Artentus/ModMyFactory2/files/5645167/ptBR.zip)

**Comment by Artentus** [comment]
Thank you for translating!  
I believe the expected format is 'pt-br', I'll sort this out.

You cannot commit to someone elses repo but you can fork it and then create a pull request with your changes.
