### ISSUE TITLE
Requires login to download mods, but does not explain how to create a log in

### ISSUE THREAD

**Issue by ah42** [Artentus/ModMyFactory2#24]
When I try to download mods with this tool, it says I need to log in, but does not indicate how or where to create an account. I do not need any log in to download mods normally in-game.

**Comment by Artentus** [comment]
Downloading mods from the official server requires a valid factorio.com login. It's the same ingame, at some point in time you have to have logged in or you wound't be able to download mods.

Anyway, it's your factorio.com login that is required there, the same you'd use to log in on the website.

**Comment by ah42** [comment]
I've never logged in to the factorio website before. I didn't know they had accounts, thank you. In-game identifies me by my Steam account.

**Comment by Artentus** [comment]
If you bought the game through Steam a "minimal" account was automatically created for you. You should be able to extend it to a full account somewhere in the games options according to the FAQ. Can't tell you anything more specific since I haven't done this personally.
