### ISSUE TITLE
Window closes after trying to make a shortcut and it deletes the ModMyFactoryGUI.exe file

### ISSUE THREAD

**Issue by BlueWeabo** [Artentus/ModMyFactory2#25]
After I extract the zip folder and open the app and create myself a modpack and want to create a factorio shortcut it closes the window before I can type something and save it. Then when I tried to open it again the .exe file wasn't there. When I tried to extract it again it said that my access was denied. When I use the sip file to create a shortcut it works fine, but then I can't use the shortcut as it can't find the file.

**Comment by BlueWeabo** [comment]
Okay it seems like it was my antivirus.... don't know why

**Comment by Artentus** [comment]
Ah that explains things. I was trying to figure out how MMF could have deleted itself but was unable to find anything.

I wasn't aware MMF was triggering any AV software but there is not much I can do about it. The developer of the AV probably has to whitelist it, but I'm probably too small a fish for them to care.

**Comment by BlueWeabo** [comment]
Yeah it was somehow classifying it as a virus but i was able to make it whitelisted for my own AV

**Comment by BlueWeabo** [comment]
Yeah it was somehow classifying it as a virus but i was able to make it whitelisted for my own AV

**Comment by BlueWeabo** [comment]
Yeah it was somehow classifying it as a virus but i was able to make it whitelisted for my own AV
