### ISSUE TITLE
Unable to connect to the Factorio Mod servers.

### ISSUE THREAD

**Issue by TR-Mord-Sith** [Artentus/ModMyFactory2#28]
Hey, not sure how to debug this one but I've pulled in some mods, and now when I go to check the mod library for anything else interesting I get "A server-side error occured. please try again later."

I will note that my "Router" (It's a Home Hub 3000 which is notorious for being a POS) has been on the blink and if your app is relying on UPnP that might be where the issue is, but that's an assumption I can't exactly test and may not make sense just to poll a server.

**Comment by herman925** [comment]
I am having this problem too and not sure where the issue comes from

**Comment by TR-Mord-Sith** [comment]
Additionally I can apparently update the mods I've selected previously, odd behavior.

**Comment by herman925** [comment]
I echo that. This is the same in my recent use of Modmyfactory too

**Comment by JonAdamsFromNC** [comment]
Same issue for me
Related to [this](https://forums.factorio.com/viewtopic.php?f=189&t=94119) forum post?

**Comment by Artentus** [comment]
I'm working on it right now, expect a fix later this night
