### ISSUE TITLE
All Mods are disabled and unable to enable mods

### ISSUE THREAD

**Issue by brendanmeyer** [Artentus/ModMyFactory2#31]
Hey, great program.

Was using 4.2.2.24 with Factorio 1.0 (Steam install) and everything was working
but after updateing to Factoro 1.1.x all the mods became disabled, and even when "enabling" them in ModMyFactory2, when I click Launch, it doesn't enable any mods now.

It doesn't seem to edit the modslist.json
Or save any of my Settings in the application

Thank you
Brendan

**Comment by Artentus** [comment]
Your existing 1.0 mods will not work with 1.1, that's why MMF keeps entirely separate mod lists for different major versions of Factorio. You'll have to re-download you mods for 1.1 for the moment. I'm looking into adding a feature that lets you upgrade your old mod lists to a new Factorio version.

**Comment by brendanmeyer** [comment]
Ah that makes sense. Thought also having that feature would great.
