### ISSUE TITLE
Getting a crash after searching for a mod then searching again

### ISSUE THREAD

**Issue by BlueWeabo** [Artentus/ModMyFactory2#37]
I tried using the mod manager from the program, but it crashed for some reason when i searched for a different mod Here is the log file
[log_20210217.txt](https://github.com/Artentus/ModMyFactory2/files/5998196/log_20210217.txt)

**Comment by Artentus** [comment]
This is not actually related to the searching, rather the specific mod you searched for.
If you can still recall which mod it was I can take a look at it.

**Comment by BlueWeabo** [comment]
I found out the mod again  it was Space Exploration
and i clicked on it and it crashed.... yes i just got it again as i was searching if i had it downloaded and i didn't tired to download it crash

**Comment by BlueWeabo** [comment]
I also looked into the folder and i had it installed... I am not sure what happened, but it doesn't recognize it anymore as installed and doesn't show it in the other mods i have installed.

**Comment by Artentus** [comment]
I found the issue, will be fixed in the next release
