### ISSUE TITLE
Won't open after crash

### ISSUE THREAD

**Issue by szentigrad3** [Artentus/ModMyFactory2#5]
so i tried using unselect all mods and the app crashed and then after trying to open it after double clicking the exe does nothing(app doesn't open)

[log_20200612.txt](https://github.com/Artentus/ModMyFactory2/files/4770197/log_20200612.txt)

edit: seems something to do with this
https://www.dropbox.com/s/t17l656mtt1y77g/modpacks.json?dl=0

also https://mods.factorio.com/mod/Upgradable_Mining_Drones says its an invalid mod and also doesn't show in my mod list

**Comment by Artentus** [comment]
Your modpacks.json file seems to be damaged. Not really sure how this could've happened but for the time being deleting it will get rid of the crash (it will however reset all your modpacks).

I will take a look at that mod.

**Comment by szentigrad3** [comment]
i have deleted and it opens again but when i turn and unselect all mods it just crashes again

**Comment by szentigrad3** [comment]
also wanted to ask how do you update the mods, as i don't see that option yet

**Comment by Artentus** [comment]
Not yet implemented
